# Sidebar/About Me
about:
  name: "Maria"
  image: "images/myself.png"
  bio: "I work mainly with **SQL** and **Power BI**, but I’m learning **Python** and expanding my skills in machine learning and data science processes. I’m passionate about using data to uncover insights and create impactful visualisations."
