title: Maria's Data Science Portfolio
description: Portfolio of Maria, Senior Digital Analytics Developer
author: Maria
baseurl: "" 
url: "https://marialwatton.github.io/DataPortfolio"
theme: jekyll-theme-slate   # example theme with sidebar support

# Sidebar navigation
nav:
  - title: About Me
    url: /about
  - title: Projects
    url: /projects
  - title: Skills
    url: /skills
  - title: Contact
    url: /contact
